title: AI Conferences
remark: IoT-oriented

description: Countdowns to top IoT, ML, CV, NLP, DM conferences
author: Hao Zhou
maintainers: Hao Zhou

domain: "iot-psu.github.io/ai-deadlines/"
baseurl: "ai-deadlines"

github_username: iot-psu
github_repo: ai-deadlines

markdown: kramdown
